<link rel="stylesheet" href="{{asset('/asset/plugins/fontawesome-free/css/all.min.css')}}">
<link rel="stylesheet" href="{{asset('/asset/dist/css/adminlte.min.css')}}">
<link rel="stylesheet" href="{{asset('/asset/plugins/toastr/toastr.min.css')}}">
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('/asset/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('/asset/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
<!-- fullCalendar -->
<link rel="stylesheet" href="{{asset('/asset/plugins/fullcalendar/main.min.css')}}">
<link rel="stylesheet" href="{{asset('/asset/plugins/fullcalendar-daygrid/main.min.css')}}">
<link rel="stylesheet" href="{{asset('/asset/plugins/fullcalendar-timegrid/main.min.css')}}">
<link rel="stylesheet" href="{{asset('/asset/plugins/fullcalendar-bootstrap/main.min.css')}}">